/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddFriendRouteImport } from './routes/add-friend'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SetupProfileRouteImport } from './routes/setup-profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFriendRoute = AddFriendRouteImport.update({
  id: '/add-friend',
  path: '/add-friend',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProfileRoute = SetupProfileRouteImport.update({
  id: '/setup-profile',
  path: '/setup-profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-friend': typeof AddFriendRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-profile': typeof SetupProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-friend': typeof AddFriendRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-profile': typeof SetupProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-friend': typeof AddFriendRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-profile': typeof SetupProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/add-friend' | '/auth' | '/home' | '/onboarding' | '/setup-profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-friend' | '/auth' | '/home' | '/onboarding' | '/setup-profile'
  id:
    | '__root__'
    | '/'
    | '/add-friend'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/setup-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFriendRoute: typeof AddFriendRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  SetupProfileRoute: typeof SetupProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-friend': {
      id: '/add-friend'
      path: '/add-friend'
      fullPath: '/add-friend'
      preLoaderRoute: typeof AddFriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-profile': {
      id: '/setup-profile'
      path: '/setup-profile'
      fullPath: '/setup-profile'
      preLoaderRoute: typeof SetupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFriendRoute: AddFriendRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  SetupProfileRoute: SetupProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
