/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddFriendRouteImport } from './routes/add-friend'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SetupProfileRouteImport } from './routes/setup-profile'
import { Route as TramRouteImport } from './routes/tram'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as FriendsIndexRouteImport } from './routes/friends.index'
import { Route as FriendsRequestsRouteImport } from './routes/friends.requests'
import { Route as GatherIndexRouteImport } from './routes/gather.index'
import { Route as GatherIdRouteImport } from './routes/gather.$id'
import { Route as GatherNewRouteImport } from './routes/gather.new'
import { Route as NearbyIndexRouteImport } from './routes/nearby.index'
import { Route as NearbyFiltersRouteImport } from './routes/nearby.filters'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as ApiAuthAccountDeletionRouteImport } from './routes/api/auth/account-deletion'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as GatherIdManageRouteImport } from './routes/gather.$id_.manage'
import { Route as ApiDevAuthSessionRouteImport } from './routes/api/dev/auth/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFriendRoute = AddFriendRouteImport.update({
  id: '/add-friend',
  path: '/add-friend',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProfileRoute = SetupProfileRouteImport.update({
  id: '/setup-profile',
  path: '/setup-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TramRoute = TramRouteImport.update({
  id: '/tram',
  path: '/tram',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRequestsRoute = FriendsRequestsRouteImport.update({
  id: '/friends/requests',
  path: '/friends/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const GatherIndexRoute = GatherIndexRouteImport.update({
  id: '/gather/',
  path: '/gather/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatherIdRoute = GatherIdRouteImport.update({
  id: '/gather/$id',
  path: '/gather/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GatherNewRoute = GatherNewRouteImport.update({
  id: '/gather/new',
  path: '/gather/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyIndexRoute = NearbyIndexRouteImport.update({
  id: '/nearby/',
  path: '/nearby/',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyFiltersRoute = NearbyFiltersRouteImport.update({
  id: '/nearby/filters',
  path: '/nearby/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAccountDeletionRoute = ApiAuthAccountDeletionRouteImport.update({
  id: '/api/auth/account-deletion',
  path: '/api/auth/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const GatherIdManageRoute = GatherIdManageRouteImport.update({
  id: '/gather/$id_/manage',
  path: '/gather/$id/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevAuthSessionRoute = ApiDevAuthSessionRouteImport.update({
  id: '/api/dev/auth/session',
  path: '/api/dev/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-friend': typeof AddFriendRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-profile': typeof SetupProfileRoute
  '/tram': typeof TramRoute
  '/widgets': typeof WidgetsRoute
  '/chat/$id': typeof ChatIdRoute
  '/friends/requests': typeof FriendsRequestsRoute
  '/gather/$id': typeof GatherIdRoute
  '/gather/new': typeof GatherNewRoute
  '/nearby/filters': typeof NearbyFiltersRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/chat/': typeof ChatIndexRoute
  '/friends/': typeof FriendsIndexRoute
  '/gather/': typeof GatherIndexRoute
  '/nearby/': typeof NearbyIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/account-deletion': typeof ApiAuthAccountDeletionRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/gather/$id/manage': typeof GatherIdManageRoute
  '/api/dev/auth/session': typeof ApiDevAuthSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-friend': typeof AddFriendRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-profile': typeof SetupProfileRoute
  '/tram': typeof TramRoute
  '/widgets': typeof WidgetsRoute
  '/chat/$id': typeof ChatIdRoute
  '/friends/requests': typeof FriendsRequestsRoute
  '/gather/$id': typeof GatherIdRoute
  '/gather/new': typeof GatherNewRoute
  '/nearby/filters': typeof NearbyFiltersRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/chat': typeof ChatIndexRoute
  '/friends': typeof FriendsIndexRoute
  '/gather': typeof GatherIndexRoute
  '/nearby': typeof NearbyIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/account-deletion': typeof ApiAuthAccountDeletionRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/gather/$id/manage': typeof GatherIdManageRoute
  '/api/dev/auth/session': typeof ApiDevAuthSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-friend': typeof AddFriendRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-profile': typeof SetupProfileRoute
  '/tram': typeof TramRoute
  '/widgets': typeof WidgetsRoute
  '/chat/$id': typeof ChatIdRoute
  '/friends/requests': typeof FriendsRequestsRoute
  '/gather/$id': typeof GatherIdRoute
  '/gather/new': typeof GatherNewRoute
  '/nearby/filters': typeof NearbyFiltersRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/chat/': typeof ChatIndexRoute
  '/friends/': typeof FriendsIndexRoute
  '/gather/': typeof GatherIndexRoute
  '/nearby/': typeof NearbyIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/account-deletion': typeof ApiAuthAccountDeletionRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/gather/$id_/manage': typeof GatherIdManageRoute
  '/api/dev/auth/session': typeof ApiDevAuthSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-friend'
    | '/auth'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/setup-profile'
    | '/tram'
    | '/widgets'
    | '/chat/$id'
    | '/friends/requests'
    | '/gather/$id'
    | '/gather/new'
    | '/nearby/filters'
    | '/profile/$id'
    | '/settings/privacy'
    | '/chat/'
    | '/friends/'
    | '/gather/'
    | '/nearby/'
    | '/profile/'
    | '/settings/'
    | '/api/auth/account-deletion'
    | '/api/auth/me'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/gather/$id/manage'
    | '/api/dev/auth/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-friend'
    | '/auth'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/setup-profile'
    | '/tram'
    | '/widgets'
    | '/chat/$id'
    | '/friends/requests'
    | '/gather/$id'
    | '/gather/new'
    | '/nearby/filters'
    | '/profile/$id'
    | '/settings/privacy'
    | '/chat'
    | '/friends'
    | '/gather'
    | '/nearby'
    | '/profile'
    | '/settings'
    | '/api/auth/account-deletion'
    | '/api/auth/me'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/gather/$id/manage'
    | '/api/dev/auth/session'
  id:
    | '__root__'
    | '/'
    | '/add-friend'
    | '/auth'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/setup-profile'
    | '/tram'
    | '/widgets'
    | '/chat/$id'
    | '/friends/requests'
    | '/gather/$id'
    | '/gather/new'
    | '/nearby/filters'
    | '/profile/$id'
    | '/settings/privacy'
    | '/chat/'
    | '/friends/'
    | '/gather/'
    | '/nearby/'
    | '/profile/'
    | '/settings/'
    | '/api/auth/account-deletion'
    | '/api/auth/me'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/gather/$id_/manage'
    | '/api/dev/auth/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFriendRoute: typeof AddFriendRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  SetupProfileRoute: typeof SetupProfileRoute
  TramRoute: typeof TramRoute
  WidgetsRoute: typeof WidgetsRoute
  ChatIdRoute: typeof ChatIdRoute
  FriendsRequestsRoute: typeof FriendsRequestsRoute
  GatherIdRoute: typeof GatherIdRoute
  GatherNewRoute: typeof GatherNewRoute
  NearbyFiltersRoute: typeof NearbyFiltersRoute
  ProfileIdRoute: typeof ProfileIdRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  ChatIndexRoute: typeof ChatIndexRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
  GatherIndexRoute: typeof GatherIndexRoute
  NearbyIndexRoute: typeof NearbyIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthAccountDeletionRoute: typeof ApiAuthAccountDeletionRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  GatherIdManageRoute: typeof GatherIdManageRoute
  ApiDevAuthSessionRoute: typeof ApiDevAuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-friend': {
      id: '/add-friend'
      path: '/add-friend'
      fullPath: '/add-friend'
      preLoaderRoute: typeof AddFriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-profile': {
      id: '/setup-profile'
      path: '/setup-profile'
      fullPath: '/setup-profile'
      preLoaderRoute: typeof SetupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tram': {
      id: '/tram'
      path: '/tram'
      fullPath: '/tram'
      preLoaderRoute: typeof TramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/': {
      id: '/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/requests': {
      id: '/friends/requests'
      path: '/friends/requests'
      fullPath: '/friends/requests'
      preLoaderRoute: typeof FriendsRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gather/': {
      id: '/gather/'
      path: '/gather'
      fullPath: '/gather/'
      preLoaderRoute: typeof GatherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gather/$id': {
      id: '/gather/$id'
      path: '/gather/$id'
      fullPath: '/gather/$id'
      preLoaderRoute: typeof GatherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gather/new': {
      id: '/gather/new'
      path: '/gather/new'
      fullPath: '/gather/new'
      preLoaderRoute: typeof GatherNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby/': {
      id: '/nearby/'
      path: '/nearby'
      fullPath: '/nearby/'
      preLoaderRoute: typeof NearbyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby/filters': {
      id: '/nearby/filters'
      path: '/nearby/filters'
      fullPath: '/nearby/filters'
      preLoaderRoute: typeof NearbyFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/account-deletion': {
      id: '/api/auth/account-deletion'
      path: '/api/auth/account-deletion'
      fullPath: '/api/auth/account-deletion'
      preLoaderRoute: typeof ApiAuthAccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gather/$id_/manage': {
      id: '/gather/$id_/manage'
      path: '/gather/$id/manage'
      fullPath: '/gather/$id/manage'
      preLoaderRoute: typeof GatherIdManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/auth/session': {
      id: '/api/dev/auth/session'
      path: '/api/dev/auth/session'
      fullPath: '/api/dev/auth/session'
      preLoaderRoute: typeof ApiDevAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFriendRoute: AddFriendRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  SetupProfileRoute: SetupProfileRoute,
  TramRoute: TramRoute,
  WidgetsRoute: WidgetsRoute,
  ChatIdRoute: ChatIdRoute,
  FriendsRequestsRoute: FriendsRequestsRoute,
  GatherIdRoute: GatherIdRoute,
  GatherNewRoute: GatherNewRoute,
  NearbyFiltersRoute: NearbyFiltersRoute,
  ProfileIdRoute: ProfileIdRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  ChatIndexRoute: ChatIndexRoute,
  FriendsIndexRoute: FriendsIndexRoute,
  GatherIndexRoute: GatherIndexRoute,
  NearbyIndexRoute: NearbyIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthAccountDeletionRoute: ApiAuthAccountDeletionRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  GatherIdManageRoute: GatherIdManageRoute,
  ApiDevAuthSessionRoute: ApiDevAuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
